name: CI Pipeline MLflow & Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Setup Job & Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    # Check Env
    - name: Check Env
      run: |
        python --version
        pip --version

    # Install Dependencies Dasar
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn seaborn matplotlib

    # 1. Run MLflow Project (Masuk ke folder dulu agar tidak dianggap repo git asing)
    - name: Run mlflow project
      run: |
        cd MLProject
        # Gunakan titik (.) untuk menjalankan project di direktori saat ini
        mlflow run . --env-manager=local

    # 2. Mengambil run_id MLflow (Path kembali ke MLProject/mlruns karena kita run di dalam folder)
    - name: Get latest MLflow run_id
      run: |
        echo "Listing MLProject/mlruns/0/ content:"
        ls -F MLProject/mlruns/0/

        # Filter folder 'datasets' dan 'tags' agar tidak salah ambil
        LATEST_RUN=$(ls -td MLProject/mlruns/0/*/ | grep -v "/datasets/" | grep -v "/tags/" | head -n 1)
        
        if [ -z "$LATEST_RUN" ]; then
          echo "Error: No valid run folder found in MLProject/mlruns/0/!"
          exit 1
        fi

        RUN_ID=$(basename "$LATEST_RUN")
        
        echo "Detected Valid Run ID: $RUN_ID"
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    # Upload to GitHub
    - name: Upload to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns-experiment
        path: MLProject/mlruns

    # 3. Build Docker Model (Masuk ke folder MLProject agar path 'mlruns' terbaca lokal)
    - name: Build Docker Model
      run: |
        echo "Building Docker for Run ID: ${{ env.RUN_ID }}"
        
        if [ -z "${{ env.RUN_ID }}" ]; then
          echo "Error: RUN_ID is empty."
          exit 1
        fi
        
        # Masuk ke folder MLProject karena 'mlflow run' tadi dijalankan di sini, database 'mlruns' juga ada di sini.
        cd MLProject
        
        mlflow models build-docker \
          --model-uri "runs:/${{ env.RUN_ID }}/model" \
          --name "my-mlops-model:latest" \
          --enable-mlserver

    # Log in ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Tag Docker Image
    - name: Tag Docker Image
      run: |
        docker tag my-mlops-model:latest ${{ secrets.DOCKER_USERNAME }}/submission-mlops:v1

    # Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-mlops:v1