name: CI Pipeline MLflow & Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Setup Job & Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    # Check Env
    - name: Check Env
      run: |
        python --version
        pip --version

    # Install Dependencies Dasar
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn seaborn matplotlib

    # Run MLflow Project
    - name: Run mlflow project
      run: |
        mlflow run MLProject --env-manager=local

    # Mengambil run_id MLflow (Filter folder 'datasets')
    - name: Get latest MLflow run_id
      run: |
        echo "Listing mlruns/0/ content for debugging:"
        ls -F mlruns/0/

        # Cari folder terbaru di mlruns/0/, TAPI abaikan folder 'datasets', 'tags', dll
        # grep -v artinya "kecuali"
        LATEST_RUN=$(ls -td mlruns/0/*/ | grep -v "/datasets/" | grep -v "/tags/" | head -n 1)
        
        if [ -z "$LATEST_RUN" ]; then
          echo "Error: No valid run folder found!"
          exit 1
        fi

        RUN_ID=$(basename "$LATEST_RUN")
        
        echo "Detected Valid Run ID: $RUN_ID"
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    # Upload to GitHub
    - name: Upload to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns-experiment
        path: mlruns

    # Build Docker Model
    - name: Build Docker Model
      run: |
        echo "Building Docker for Run ID: ${{ env.RUN_ID }}"
        
        # Validasi jika ID kosong
        if [ -z "${{ env.RUN_ID }}" ]; then
          echo "Error: RUN_ID is empty. Pipeline stopped."
          exit 1
        fi
        
        # JANGAN cd ke MLProject.
        # Kita tetap di root agar MLflow bisa membaca folder './mlruns' yang baru saja dibuat.
        
        mlflow models build-docker \
          --model-uri "runs:/${{ env.RUN_ID }}/model" \
          --name "my-mlops-model:latest" \
          --enable-mlserver

    # Log in ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Tag Docker Image
    - name: Tag Docker Image
      run: |
        docker tag my-mlops-model:latest ${{ secrets.DOCKER_USERNAME }}/submission-mlops:v1

    # Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-mlops:v1