name: CI Pipeline MLflow & Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Setup Job & Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    # Check Env
    - name: Check Env
      run: |
        python --version
        pip --version

    # Install Dependencies Dasar
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn seaborn matplotlib
        # Jika modelling.py butuh library lain, install di sini juga

    # Run MLflow Project
    - name: Run mlflow project
      run: |
        cd MLProject
        python modelling.py

    # Mengambil run_id MLflow 
    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        # Cari folder terbaru, TAPI abaikan folder bernama 'datasets' dan 'meta.yaml'
        LATEST_RUN=$(ls -td MLProject/mlruns/0/* | grep -v "datasets" | grep -v "meta.yaml" | head -1)
        RUN_ID=$(basename "$LATEST_RUN")
        echo "Detected Run ID: $RUN_ID"
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    # Upload to GitHub
    - name: Upload to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns-experiment
        path: MLProject/mlruns

    # Build Docker Model
    - name: Build Docker Model
      env:
        RUN_ID: ${{ steps.get_run_id.outputs.run_id }}
      run: |
        echo "Building Docker for Run ID: $RUN_ID"
        # Format URI: runs:/<run_id>/<nama_folder_model_di_modelling_py>
        # Asumsi di modelling.py anda log model dengan nama "model" atau "best_model"
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "my-mlops-model:latest" \
          --enable-mlserver

    # Log in ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Tag Docker Image
    - name: Tag Docker Image
      run: |
        docker tag my-mlops-model:latest ${{ secrets.DOCKER_USERNAME }}/submission-mlops:v1

    # Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-mlops:v1